version: "3.9"

services:
  db:
    image: mysql:8.4
    container_name: finances-db
    environment:
      MYSQL_DATABASE: finances_db
      MYSQL_USER: apiuser
      MYSQL_PASSWORD: apipassword
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: finances-app
    environment:
      DB_URL: jdbc:mysql://db:3306/finances_db
      DB_USERNAME: apiuser
      DB_PASSWORD: apipassword
      DB_DDL_AUTO: update
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
